COUNTRIES = [
    "Great Britain",
    "Ireland",
    "USA",
    "Italy",
    "Malta",
    "Portugal",
    "Spain",
    "France",
    "Belgium",
    "Luxembourg",
    "the Netherlands",
    "East Frisia",
    "Germany",
    "Austria",
    "Swiss",
    "Iceland",
    "Denmark",
    "Norway",
    "Sweden",
    "Finland",
    "Estonia",
    "Latvia",
    "Lithuania",
    "Poland",
    "Czech Republic",
    "Slovakia",
    "Hungary",
    "Romania",
    "Bulgaria",
    "Bosnia",
    "Croatia",
    "Kosovo",
    "Macedonia",
    "Montenegro",
    "Serbia",
    "Slovenia",
    "Albania",
    "Greece",
    "Russia",
    "Belarus",
    "Moldova",
    "Ukraine",
    "Armenia",
    "Azerbaijan",
    "Georgia",
    "Kazakhstan",
    "Turkey",
    "Arabia",
    "Israel",
    "China",
    "India",
    "Japan",
    "Korea",
    "Vietnam"
]
